# Generated by Django 2.2.7 on 2019-11-11 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('web_page', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente_krkn',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'colaborador_krkn',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'proyecto_krkn_galeria',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'puesto_krkn',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto_krkn_tecnologia',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', related_query_name='cliente', to='projects.Cliente')),
                ('tecnologias', models.ManyToManyField(to='projects.Tecnologia')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'proyecto_krkn',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('alt', models.CharField(max_length=50)),
                ('src', models.ImageField(blank=True, null=True, upload_to='projects/images/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('galeria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.Galeria')),
            ],
            options={
                'db_table': 'proyecto_krkn_imagen_galeria',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='galeria',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerias', to='projects.Proyecto'),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('tipo', models.CharField(choices=[('Repositorio', 'Repositorio'), ('Avance', 'Avance'), ('Informe', 'Informe'), ('Artículo', 'Artículo'), ('Video', 'Video'), ('Otro', 'Otro')], default='Repositorio', max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='projects.Proyecto')),
            ],
            options={
                'db_table': 'proyecto_krkn_archivo',
            },
        ),
        migrations.CreateModel(
            name='RolProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_proyecto', to='projects.Colaborador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='projects.Proyecto')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Puesto')),
            ],
            options={
                'db_table': 'proyecto_krkn_rol',
                'ordering': ['-created'],
                'unique_together': {('proyecto', 'puesto', 'colaborador')},
            },
        ),
    ]
