# Generated by Django 2.2.7 on 2019-11-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_proyecto_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='logotipo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
