# Generated by Django 2.2.7 on 2019-12-05 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tecnologia_logotipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='edo_civil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fecha_nac',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='profesion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='recidencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='rfc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
