# Generated by Django 2.2.7 on 2019-12-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191204_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='edo_civil',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='fecha_nac',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='recidencia',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='rfc',
        ),
    ]
