# Generated by Django 2.2.7 on 2019-12-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191206_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='edo_civil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='profesion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='recidencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='rfc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
