# Generated by Django 2.2.7 on 2019-12-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20191206_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
