# Generated by Django 2.2.7 on 2019-12-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_colaborador_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='projects.Colaborador')),
            ],
            options={
                'db_table': 'colaborador_educacion_krkn',
            },
        ),
    ]
