# Generated by Django 2.2.7 on 2019-12-09 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_educacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='projects.Colaborador'),
        ),
        migrations.DeleteModel(
            name='RolProyecto',
        ),
    ]
