# Generated by Django 2.2.7 on 2019-12-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20191209_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_proyecto', to='projects.Colaborador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='projects.Proyecto')),
            ],
            options={
                'db_table': 'proyecto_krkn_rol',
                'unique_together': {('proyecto', 'colaborador')},
            },
        ),
    ]
