# Generated by Django 2.2.7 on 2019-12-09 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_colaboradorproyecto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='colaboradorproyecto',
            table='colaborador_proyecto',
        ),
    ]
