# Generated by Django 2.2.7 on 2019-12-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20191209_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorproyecto',
            name='actividades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
