# Generated by Django 2.2.7 on 2019-12-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_colaboradorproyecto_actividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorproyecto',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
