# Generated by Django 2.2.7 on 2019-12-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_colaboradorproyecto_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividades', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='projects.Cliente')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_laboral', to='projects.Colaborador')),
            ],
            options={
                'db_table': 'colaborador_cliente',
                'unique_together': {('cliente', 'colaborador')},
            },
        ),
    ]
