# Generated by Django 2.2.7 on 2019-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_colaboradorcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
