# Generated by Django 2.2.7 on 2019-12-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_cliente_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcliente',
            name='puesto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
