# Generated by Django 2.2.7 on 2019-12-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_colaboradorcliente_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='exp_laboral_resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
