# Generated by Django 2.2.7 on 2019-12-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_colaborador_exp_laboral_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='exp_tec_resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
