# Generated by Django 2.2.7 on 2019-12-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_colaborador_exp_tec_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='portafolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('Proyecto', 'Proyecto'), ('Front End', 'Front End Development'), ('Diseño', 'Diseño Gráfico'), ('Aplicación Mobile', 'Aplicación Mobile'), ('Back End', 'Back End Development'), ('Otro', 'Otro')], default='Front End', max_length=50),
        ),
    ]
