# Generated by Django 2.2.7 on 2019-12-20 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20191213_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcliente',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaboradorcliente',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
