# Generated by Django 2.2.7 on 2019-12-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20191220_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradorcliente',
            options={'ordering': ['-fecha_inicio', '-fecha_fin']},
        ),
        migrations.AddField(
            model_name='colaboradorcliente',
            name='actulidad',
            field=models.BooleanField(default=False),
        ),
    ]
