# Generated by Django 2.2.7 on 2019-12-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20191220_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradorcliente',
            old_name='actulidad',
            new_name='actualidad',
        ),
    ]
