# Generated by Django 2.2.7 on 2020-01-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20191220_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradorcliente',
            options={'ordering': ['-actualidad', '-fecha_inicio', '-fecha_fin']},
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'ordering': ['-periodo_fin']},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Cliente'),
        ),
    ]
